"""empty message

Revision ID: 4558ee3a4162
Revises: 8f9e964c6733
Create Date: 2026-03-22 16:45:18.677236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4558ee3a4162'
down_revision = '8f9e964c6733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
